### ISSUE TITLE
Make it possible to run without chroot

### ISSUE THREAD

**Issue by YtvwlD** [grufwub/gophor#11]
I wanted to serve my blog over Gopher for quite some time, but I didn't manage to get any of the servers to run because most of them are quite old, so I think it's really great that this software exists.
So, today I tried to get this to run with a shared hosting provider, but it failed because it couldn't chroot at start.

It would be nice if you were to add a parameter with which the software could run without the possibility to chroot.

**Comment by grufwub** [comment]
Hey thanks for the input! Been working on this over the course of this evening, will continue on with it tomorrow and try get something out ASAP. I just want to ensure that supplied paths are sanitized correctly in this case to prevent directory traversal attacks :)

**Comment by grufwub** [comment]
We got a new `-rootless` flag in development now, i'm just doing some more testing and going to neaten up the additions I've made before we hit a pre-release :D

**Comment by grufwub** [comment]
Pre-release out! https://github.com/grufwub/gophor/releases/tag/v0.6-beta-PR1

Let me know if you have any issues :+1:

**Comment by YtvwlD** [comment]
Thank you very much. I just have three static pages and a main menu yet, but it seems to work. :tada:
