### ISSUE TITLE
Add an option to remove parts of the IP addresses from the access log

### ISSUE THREAD

**Issue by YtvwlD** [grufwub/gophor#12]
I'd like to see what pages people access but I'm not that keen on collecting IP addresses.
It would be really nice, if the last half of the addresses could be removed from the access log – or the whole address, that's probably easier.

**Comment by grufwub** [comment]
I got to work and implemented that this evening :), there's a new pre-release out with this feature: https://github.com/grufwub/gophor/releases/tag/v0.6-beta-PR2

I opted to totally remove IP addresses if requested, and timestamps in logs are also now toggleable.

**Comment by YtvwlD** [comment]
Great :)
