### ISSUE TITLE
server sends RST when used with phetch

### ISSUE THREAD

**Issue by YtvwlD** [grufwub/gophor#13]
Hey, I've got a weird problem: I can't read big pages (about 20k) with phetch (it's a small terminal client).

I tried debugging this with Wireshark - and by switching server and client. And I could only reproduce this with gophor + phetch.

In Wireshark, I can see that the server sends a RST at some point in the transmission - on all pages, but just when used with phetch. Small pages still load successfully, because the RST comes after the content has been transferred.

I'm not quite sure what invokes this behaviour (and whether it's a bug in gophor or phetch), but what I noticed is that phetch sends the path and `\r\n` in two seperate TCP packets whereas lynx and castor (the other clients I tested with) send them both in a single packet.

**Comment by grufwub** [comment]
Yes I've noticed some weird issues with phetch, I actually just submitted an issue with fix that got PR'd yesterday for something unrelated! Though not to say this couldn't be a gophor issue. I shall do some investigating!

**Comment by grufwub** [comment]
Does it just attempt to load and display a blank screen instead? I'm testing introducing cgi-bin and executable gophermap support in the development branch, and while also using phetch for testing I'm finding that some scripts outputted as text for the client to read as item type 0 (regular file) just show as a blank screen. But when I use cgo or lynx I have no issues.

**Comment by YtvwlD** [comment]
No, it displays "Connection reset by peer (os error 104)" at the bottom of the screen and stays at the previous page.

**Comment by grufwub** [comment]
I'm thinking that it might be this in RFC 1436:
```
Textfile Entity

TextFile  ::= {TextBlock} Lastline

Note:  Lines beginning with periods must be prepended with an extra
     period to ensure that the transmission is not terminated early.
     The client should strip extra periods at the beginning of the line.
```

The proposed GopherII protocol (2015, as oppoosed to RFC1436 from 1993) suggests that servers can opt whether to end text files on a last line or not. Following this I opted not to do this for text files as it meant that many clients like cgo etc would display this lastline. Text files are also not checked for these lines starting with periods. I'll have a look at the phetch code tomorrow, maybe recompile with some more print statements, see if I'm right about this or if phetch is running into its own issues.

**Comment by grufwub** [comment]
Thank you again for all these issue submitted to help guide development :grinning:

**Comment by YtvwlD** [comment]
:D

I'm not sure the content sent by the server is relevant here as the server sends the RST and not the client.
What I also noticed is that the two packets containing the path and `\r\n` are both send by phetch with the push TCP flag set. I don't know if this is strictly wrong but I would have thought that just the last one would get the flag.

**Comment by grufwub** [comment]
Even with the packets sent as 2 different parts, it should still get set kind of output. The socket reads until it gets a count < bufsize, basically EOF. It then reads up to either the first `\t` or `\r\n` in the request, or if none reached it returns an empty string which should just return the root gophermap / directory listing.

A closed connection with no output sounds like the server possibly hitting the max RFC1436 selector length (which is 255). In this case it will just close the connection, though I really should send an error here. This is also changing in the next update with the feature addition of CGI-bin support, URL queries etc.

**Comment by YtvwlD** [comment]
Sorry for responding that late – I was a bit busy the last two days.

I patched phetch to send the whole request in a single packet and that indeed solves the problem:

```patch
diff --git a/src/gopher.rs b/src/gopher.rs
index f43b3c2..790653c 100644
--- a/src/gopher.rs
+++ b/src/gopher.rs
@@ -207,8 +207,8 @@ pub fn request(host: &str, port: &str, selector: &str, tls: bool, tor: bool) ->
         .and_then(|mut socks| socks.next().ok_or_else(|| error!("Can't create socket")))?;
     let mut stream = TcpStream::connect_timeout(&sock, TCP_TIMEOUT_DURATION)?;
     stream.set_read_timeout(Some(TCP_TIMEOUT_DURATION))?;
-    stream.write_all(selector.as_ref())?;
-    stream.write_all("\r\n".as_ref())?;
+    let to_send = format!("{}\r\n", selector);
+    stream.write_all(to_send.as_ref())?;
     Ok(Stream {
         io: Box::new(stream),
         tls: false,
```

I think it's a bit weird to use TCP to send text and not having line-buffering, apparently, but I'm not sure it violates the spec.

I don't know enough about TCP to say why it results in a `RST` but gophor never `ACK`s the packet containing `\r\n`. I guess this leads to the incoming buffer filling up causing the operating system to terminate the connection or something like this.

**Comment by YtvwlD** [comment]
Oh, 3a41efcc seems to have fixed it. :)

**Comment by grufwub** [comment]
> Sorry for responding that late – I was a bit busy the last two days.
> 
> I patched phetch to send the whole request in a single packet and that indeed solves the problem:
> 
> ```diff
> diff --git a/src/gopher.rs b/src/gopher.rs
> index f43b3c2..790653c 100644
> --- a/src/gopher.rs
> +++ b/src/gopher.rs
> @@ -207,8 +207,8 @@ pub fn request(host: &str, port: &str, selector: &str, tls: bool, tor: bool) ->
>          .and_then(|mut socks| socks.next().ok_or_else(|| error!("Can't create socket")))?;
>      let mut stream = TcpStream::connect_timeout(&sock, TCP_TIMEOUT_DURATION)?;
>      stream.set_read_timeout(Some(TCP_TIMEOUT_DURATION))?;
> -    stream.write_all(selector.as_ref())?;
> -    stream.write_all("\r\n".as_ref())?;
> +    let to_send = format!("{}\r\n", selector);
> +    stream.write_all(to_send.as_ref())?;
>      Ok(Stream {
>          io: Box::new(stream),
>          tls: false,
> ```
> 
> I think it's a bit weird to use TCP to send text and not having line-buffering, apparently, but I'm not sure it violates the spec.
> 
> I don't know enough about TCP to say why it results in a `RST` but gophor never `ACK`s the packet containing `\r\n`. I guess this leads to the incoming buffer filling up causing the operating system to terminate the connection or something like this.

I was thinking about this after having done the big `Request` overhaul. Especially since now we were performing a straight write to conn after rendering each individual section of a gophermap.

So I spent most of today re-writing things to work with a buffered writer instead which should mitigate any potential issues that could have been caused by spliting things up into a potentially insane number of small writes to the underlying socket. It wouldn't have taken me all day if I'd actually remembered that `bufio` was a thing and spent ages implementing my own :D
